#!/usr/bin/env python3
"""
WookViewer 테스트용 샘플 문서 생성기.

생성 파일 (test-samples/):
  - WookViewer-test.pdf   : 2페이지 영문 (FULL fidelity 검증용 — 페이지/줌/팬)
  - WookViewer-test.docx  : 한글+영문, 단락/표/특수문자 (TEXT_ONLY 검증용)
  - WookViewer-test.pptx  : 12장 슬라이드 (자연수 정렬 회귀 — slide1<...<slide10<slide11<slide12)

표준 라이브러리만 사용 — 외부 의존성 없음.
"""

import html
import os
import sys
import zipfile
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent.parent / "test-samples"
OUT_DIR.mkdir(exist_ok=True)


# ============================================================
# 1) PDF
# ============================================================
def make_pdf(path: Path) -> None:
    """최소 PDF-1.4 — 2페이지, 내장 Helvetica 폰트, 영문 텍스트."""
    out = bytearray()
    offsets: dict[int, int] = {}

    def emit(s: bytes | str) -> None:
        if isinstance(s, str):
            s = s.encode("ascii")
        out.extend(s)

    def pos() -> int:
        return len(out)

    # Header
    emit(b"%PDF-1.4\n%\xE2\xE3\xCF\xD3\n")

    # Object 1: Catalog
    offsets[1] = pos()
    emit("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")

    # Object 2: Pages
    offsets[2] = pos()
    emit("2 0 obj\n<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>\nendobj\n")

    # Object 3: Page 1
    offsets[3] = pos()
    emit(
        "3 0 obj\n"
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        "/Resources << /Font << /F1 5 0 R >> >> /Contents 6 0 R >>\n"
        "endobj\n"
    )

    # Object 4: Page 2
    offsets[4] = pos()
    emit(
        "4 0 obj\n"
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        "/Resources << /Font << /F1 5 0 R >> >> /Contents 7 0 R >>\n"
        "endobj\n"
    )

    # Object 5: Helvetica (built-in standard font)
    offsets[5] = pos()
    emit("5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")

    # Object 6: Page 1 content
    page1 = (
        "BT /F1 28 Tf 60 720 Td (WookViewer Test PDF) Tj ET\n"
        "BT /F1 14 Tf 60 680 Td (Page 1 of 2) Tj ET\n"
        "BT /F1 14 Tf 60 640 Td (This sample verifies:) Tj ET\n"
        "BT /F1 12 Tf 80 610 Td (- Page navigation \\(prev / next\\)) Tj ET\n"
        "BT /F1 12 Tf 80 590 Td (- Pinch zoom 1x to 5x) Tj ET\n"
        "BT /F1 12 Tf 80 570 Td (- Pan after zoom) Tj ET\n"
        "BT /F1 12 Tf 80 550 Td (- No banner \\(PDF is FULL fidelity\\)) Tj ET\n"
        "BT /F1 10 Tf 60 100 Td (Generated by generate_test_samples.py) Tj ET\n"
    ).encode("ascii")
    offsets[6] = pos()
    emit(f"6 0 obj\n<< /Length {len(page1)} >>\nstream\n")
    emit(page1)
    emit("\nendstream\nendobj\n")

    # Object 7: Page 2 content
    page2 = (
        "BT /F1 28 Tf 60 720 Td (WookViewer Test PDF) Tj ET\n"
        "BT /F1 14 Tf 60 680 Td (Page 2 of 2) Tj ET\n"
        "BT /F1 14 Tf 60 640 Td (Tap left arrow to go back to Page 1.) Tj ET\n"
        "BT /F1 12 Tf 60 580 Td (For Korean rendering, use the DOCX sample) Tj ET\n"
        "BT /F1 12 Tf 60 560 Td (\\(PDF Korean needs font embedding - out of scope\\).) Tj ET\n"
    ).encode("ascii")
    offsets[7] = pos()
    emit(f"7 0 obj\n<< /Length {len(page2)} >>\nstream\n")
    emit(page2)
    emit("\nendstream\nendobj\n")

    # xref table
    xref_start = pos()
    emit("xref\n0 8\n0000000000 65535 f \n")
    for i in range(1, 8):
        emit(f"{offsets[i]:010d} 00000 n \n")

    # Trailer
    emit("trailer\n<< /Size 8 /Root 1 0 R >>\nstartxref\n")
    emit(str(xref_start) + "\n%%EOF\n")

    path.write_bytes(out)
    print(f"  PDF  -> {path.name}  ({len(out):,} bytes)")


# ============================================================
# 2) DOCX
# ============================================================
def make_docx(path: Path) -> None:
    content_types = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>"""

    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>"""

    document = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    <w:p><w:r><w:t>WookViewer DOCX 테스트 문서</w:t></w:r></w:p>
    <w:p><w:r><w:t></w:t></w:r></w:p>
    <w:p><w:r><w:t>이 문서는 다음 항목을 검증합니다:</w:t></w:r></w:p>
    <w:p><w:r><w:t>• 한글 텍스트 렌더링 (Noto CJK 폴백)</w:t></w:r></w:p>
    <w:p><w:r><w:t>• 영문 + 한글 혼합 — Hello 안녕하세요 World</w:t></w:r></w:p>
    <w:p><w:r><w:t>• 단락 구분 (이 줄과 다음 줄 사이 공백)</w:t></w:r></w:p>
    <w:p><w:r><w:t></w:t></w:r></w:p>
    <w:p><w:r><w:t>• 특수문자: &lt;tag&gt; &amp; &quot;quote&quot;</w:t></w:r></w:p>
    <w:p><w:r><w:t></w:t></w:r></w:p>
    <w:p><w:r><w:t>표 테스트 — 셀이 탭으로 구분되어 보여야 함:</w:t></w:r></w:p>
    <w:tbl>
      <w:tr>
        <w:tc><w:p><w:r><w:t>이름</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>역할</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>비고</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>박설계</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>설계 리드</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>아키텍처</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>이시니어</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>구현</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>핵심 로직</w:t></w:r></w:p></w:tc>
      </w:tr>
      <w:tr>
        <w:tc><w:p><w:r><w:t>한QA</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>QA</w:t></w:r></w:p></w:tc>
        <w:tc><w:p><w:r><w:t>회귀 테스트</w:t></w:r></w:p></w:tc>
      </w:tr>
    </w:tbl>
    <w:p><w:r><w:t></w:t></w:r></w:p>
    <w:p><w:r><w:t>긴 단락 테스트입니다. 한글 텍스트가 자동 줄바꿈되어 한 페이지에 어떻게 배치되는지 확인하기 위해 충분히 긴 문장을 추가합니다. 페이지가 분할될 만큼 길게는 아니지만, 단락 안에서 자연스럽게 흐르는지 보기 위함입니다.</w:t></w:r></w:p>
    <w:p><w:r><w:t></w:t></w:r></w:p>
    <w:p><w:r><w:t>(테스트 끝)</w:t></w:r></w:p>
  </w:body>
</w:document>"""

    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", content_types)
        z.writestr("_rels/.rels", rels)
        z.writestr("word/document.xml", document)
    print(f"  DOCX -> {path.name}  ({path.stat().st_size:,} bytes)")


# ============================================================
# 3) PPTX (12 slides for natural-sort regression)
# ============================================================
def make_pptx(path: Path) -> None:
    slide_titles = [
        "1: 첫 번째 슬라이드",
        "2: 두 번째 슬라이드",
        "3: 표 테스트",
        "4: 다중 텍스트 박스",
        "5: 영문/한글 혼합 — Mixed",
        "6: 특수문자 < & >",
        "7: 일곱 번째",
        "8: 여덟 번째",
        "9: 아홉 번째",
        "10: 열 번째 (이 슬라이드가 slide2 뒤에 와야 함!)",
        "11: 열한 번째",
        "12: 마지막 — 자연수 정렬 OK",
    ]

    n = len(slide_titles)

    content_types_parts = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">',
        '  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>',
        '  <Default Extension="xml" ContentType="application/xml"/>',
        '  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>',
    ]
    for i in range(1, n + 1):
        content_types_parts.append(
            f'  <Override PartName="/ppt/slides/slide{i}.xml" '
            f'ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>'
        )
    content_types_parts.append("</Types>")
    content_types = "\n".join(content_types_parts)

    rels = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>"""

    presentation = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"/>"""

    def slide_xml(body: str) -> str:
        return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
       xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
       xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:cSld>
    <p:spTree>
{body}
    </p:spTree>
  </p:cSld>
</p:sld>"""

    def title_sp(text: str) -> str:
        safe = html.escape(text, quote=True)
        return f"      <p:sp><p:txBody><a:p><a:r><a:t>{safe}</a:t></a:r></a:p></p:txBody></p:sp>"

    def text_sp(text: str) -> str:
        safe = html.escape(text, quote=True)
        return f"      <p:sp><p:txBody><a:p><a:r><a:t>{safe}</a:t></a:r></a:p></p:txBody></p:sp>"

    def table_block() -> str:
        return """      <a:tbl>
        <a:tr>
          <a:tc><a:txBody><a:p><a:r><a:t>항목</a:t></a:r></a:p></a:txBody></a:tc>
          <a:tc><a:txBody><a:p><a:r><a:t>값</a:t></a:r></a:p></a:txBody></a:tc>
        </a:tr>
        <a:tr>
          <a:tc><a:txBody><a:p><a:r><a:t>가</a:t></a:r></a:p></a:txBody></a:tc>
          <a:tc><a:txBody><a:p><a:r><a:t>123</a:t></a:r></a:p></a:txBody></a:tc>
        </a:tr>
        <a:tr>
          <a:tc><a:txBody><a:p><a:r><a:t>나</a:t></a:r></a:p></a:txBody></a:tc>
          <a:tc><a:txBody><a:p><a:r><a:t>456</a:t></a:r></a:p></a:txBody></a:tc>
        </a:tr>
      </a:tbl>"""

    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", content_types)
        z.writestr("_rels/.rels", rels)
        z.writestr("ppt/presentation.xml", presentation)

        for i, title in enumerate(slide_titles, start=1):
            if i == 3:
                # 표 슬라이드
                body = "\n".join([title_sp(title), table_block()])
            elif i == 4:
                # 다중 텍스트 박스
                body = "\n".join([
                    title_sp(title),
                    text_sp("제목 박스"),
                    text_sp("본문 박스 1 — 여러 텍스트박스가 줄바꿈으로 구분됩니다."),
                    text_sp("본문 박스 2 — 두 번째 박스의 내용입니다."),
                ])
            elif i == 6:
                # 특수문자 — helper에서 자동 이스케이프됨
                body = "\n".join([
                    title_sp(title),
                    text_sp('XML 엔티티 디코딩 — <tag> & "quote"'),
                ])
            else:
                # 일반 텍스트
                body = "\n".join([
                    title_sp(title),
                    text_sp("이 슬라이드는 자연수 정렬을 검증합니다."),
                ])
            z.writestr(f"ppt/slides/slide{i}.xml", slide_xml(body))

    print(f"  PPTX -> {path.name}  ({path.stat().st_size:,} bytes)")


# ============================================================
def main() -> int:
    print(f"Output: {OUT_DIR}")
    print()
    make_pdf(OUT_DIR / "WookViewer-test.pdf")
    make_docx(OUT_DIR / "WookViewer-test.docx")
    make_pptx(OUT_DIR / "WookViewer-test.pptx")
    print()
    print(f"Done. Files in: {OUT_DIR}")
    for f in sorted(OUT_DIR.iterdir()):
        if f.is_file():
            print(f"  {f.name:40s}  {f.stat().st_size:>10,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
